INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 19:11:43] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 19:11:43] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 19:12:54] "GET /agregar HTTP/1.1" 200 -
ERROR:app:Exception on /agregar [POST]
Traceback (most recent call last):
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\Clase2Flask\rutas\persona\personas.py", line 23, in agregar
    return redirect(url_for['apppersona.inicio'])
                    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^
TypeError: 'function' object is not subscriptable
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 19:13:06] "[35m[1mPOST /agregar HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 19:20:15] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 19:20:19] "GET /agregar HTTP/1.1" 200 -
ERROR:app:Exception on /agregar [POST]
Traceback (most recent call last):
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\Clase2Flask\rutas\persona\personas.py", line 23, in agregar
    return redirect(url_for('apppersona.inicio'))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\helpers.py", line 222, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 1071, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 1060, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\werkzeug\routing\map.py", line 919, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'apppersona.inicio'. Did you mean 'apppersona.inicial' instead?
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 19:20:39] "[35m[1mPOST /agregar HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 19:23:33] "[32mPOST /agregar HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 19:23:33] "GET /index HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 19:26:36] "GET /index HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 19:26:52] "GET /editar/2 HTTP/1.1" 200 -
ERROR:app:Exception on /editar/2 [POST]
Traceback (most recent call last):
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\Clase2Flask\rutas\persona\personas.py", line 34, in editar
    return redirect(url_for('apppersona.editar'))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\helpers.py", line 222, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 1071, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 1060, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\werkzeug\routing\map.py", line 919, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'apppersona.editar'. Did you forget to specify values ['id']?
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 19:26:58] "[35m[1mPOST /editar/2 HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 19:28:35] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 19:28:37] "GET /editar/2 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 19:28:38] "[32mPOST /editar/2 HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 19:28:39] "GET /index HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 19:28:41] "GET /editar/2 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 19:28:45] "[32mPOST /editar/2 HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 19:28:45] "GET /index HTTP/1.1" 200 -
ERROR:app:Exception on /eliminar/2 [GET]
Traceback (most recent call last):
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\Clase2Flask\rutas\persona\personas.py", line 42, in eliminar
    return redirect(url_for('apppersona.inicio'))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\helpers.py", line 222, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 1071, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\flask\app.py", line 1060, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacco\OneDrive\Documentos\Tec9no\ProgramMultiP\Unidad2\pepFlask\Lib\site-packages\werkzeug\routing\map.py", line 919, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'apppersona.inicio'. Did you mean 'apppersona.inicial' instead?
INFO:werkzeug:127.0.0.1 - - [18/Oct/2023 19:28:48] "[35m[1mGET /eliminar/2 HTTP/1.1[0m" 500 -
